CREATE TABLE users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 telegram_id BIGINT NOT NULL UNIQUE,
 state TEXT NOT NULL DEFAULT 'new',
 is_blocked INTEGER NOT NULL DEFAULT 0 CHECK(is_blocked IN (0,1)),
 is_staff INTEGER NOT NULL DEFAULT 0 CHECK(is_staff IN (0,1)),
 is_counselor INTEGER NOT NULL DEFAULT 0 CHECK(is_counselor IN (0,1)),
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 username TEXT, telegram_sername TEXT, name TEXT, birth_date TEXT,
 "group" TEXT, phone TEXT, expectations TEXT, will_drive TEXT, trip_attendance TEXT,
 version BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE user_permissions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 telegram_id BIGINT NOT NULL, permission TEXT NOT NULL,
 granted_by BIGINT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 UNIQUE(telegram_id,permission)
);
CREATE TABLE bot_chats (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 chat_id BIGINT NOT NULL UNIQUE, chat_type TEXT NOT NULL, chat_title TEXT,
 is_active BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE processed_updates (bot_id BIGINT NOT NULL, update_id BIGINT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), PRIMARY KEY(bot_id,update_id));
CREATE TABLE broadcasts (
 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 actor BIGINT NOT NULL, audience TEXT NOT NULL, kind TEXT NOT NULL,
 source_chat BIGINT NOT NULL DEFAULT 0, source_message BIGINT NOT NULL DEFAULT 0,
 status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','running','paused','cancelled')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE outbound_messages (
 id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 chat BIGINT NOT NULL, is_group BOOLEAN NOT NULL DEFAULT false,
 priority TEXT NOT NULL CHECK(priority IN ('interactive','broadcast')),
 kind TEXT NOT NULL, body JSONB NOT NULL DEFAULT '{}',
 actor BIGINT NOT NULL DEFAULT 0, source_chat BIGINT NOT NULL DEFAULT 0, source_message BIGINT NOT NULL DEFAULT 0,
 broadcast_id BIGINT REFERENCES broadcasts(id),
 status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','sending','retry_wait','sent','failed','cancelled')),
 attempts INTEGER NOT NULL DEFAULT 0,
 next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(), published_at TIMESTAMPTZ,
 lease TEXT, lease_until TIMESTAMPTZ, telegram_message_id BIGINT,
 error_code TEXT NOT NULL DEFAULT '', traceparent TEXT NOT NULL DEFAULT '',
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 UNIQUE(broadcast_id,chat)
);
CREATE INDEX outbound_due ON outbound_messages(next_attempt_at,id) WHERE status IN ('pending','retry_wait','sending');
CREATE INDEX outbound_chat ON outbound_messages(chat,id) WHERE status IN ('pending','retry_wait','sending');
CREATE TABLE runtime_state (
 id INTEGER PRIMARY KEY CHECK(id=1),
 cooldown_until TIMESTAMPTZ NOT NULL DEFAULT now(),
 sender_worker TEXT NOT NULL DEFAULT '', sender_until TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO runtime_state(id) VALUES(1);
CREATE TABLE import_runs (source_hash TEXT PRIMARY KEY, imported_at TIMESTAMPTZ NOT NULL DEFAULT now(), users_count INTEGER NOT NULL);
CREATE TABLE milestone_notifications (epoch BIGINT NOT NULL, threshold INTEGER NOT NULL, PRIMARY KEY(epoch,threshold));
CREATE TABLE audit_events (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, actor BIGINT NOT NULL, action TEXT NOT NULL, target BIGINT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
